// frontend/src/app/sign-in/sign-in.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { InputComponent } from '../shared/components/input/input.component';

@Component({
  selector: 'app-sign-in',
  imports: [FormsModule, InputComponent ],
  templateUrl: './sign-in.component.html',
  styleUrl: './sign-in.component.css'
})
export class SignInComponent {
  email: string = '';
  password: string = '';

  signIn() {
    console.log('Email:', this.email);
    console.log('Password:', this.password);
  }
}

<div class="flex justify-center items-center h-screen">
    <form>
        <div class="mt-5 ml-5">
            <ui-label for="email">Email</ui-label>
            <!-- <input id="email" type="email" [(ngModel)]="email" name="email"> -->
            <ui-input [(ngModel)]="email" name="email" placeholder="email@example.com"></ui-input>
        </div>
        <div class="mt-5 ml-5">
            <ui-label for="password">Password</ui-label>
            <ui-input type="password"></ui-input>
        </div>
        <div class="mt-5 ml-5">
            <ui-button (click)="signIn()" type="submit">Sign In</ui-button>
        </div>
    </form>
</div>

// frontend/src/pages/SignIn.tsx
import Button from "../components/Button";
import Input from "../components/Input";

export default function SignIn() {
    return (
        <div className="flex justify-center min-h-screen w-full">
            <div className="flex flex-col w-1/5 justify-center items-center">
                <h1 className="font-bold text-3xl">Sign in</h1>

                <div className="flex flex-col mt-5 w-full">
                    <label>Email</label>
                    <Input/>
                </div>

                <div className="flex flex-col mt-5 w-full">
                    <label>Password</label>
                    <Input type="password"/>
                </div>

                <div className="flex flex-col mt-5 w-full">
                    <Button>Sign in</Button>
                </div>

                <p className="mt-5">New to Book Track? <a className="text-blue-500 hover:text-blue-600" href="#">Sign Up &gt;</a></p>
            </div>
        </div>
    )   
}
